---
 # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master stack: PathToMasterStackFile'

Parameters:
  ProjectName:
    Description: Enter the name of the project
    Type: String
  Stage:
    Description: Environment in which the resource is created
    Type: String
    AllowedValues: 
      - DEV_
      - PRN_
  Name:
    Description: Enter the name table
    Type: String
  PartitionKey:
    Description: This field is the primary key of the table. (HASH)
    Type: String
  PartitionKeyType:
    Description: Type of data that will be associated with the PartitionKey (S = String, N = Number)
    Type: String
    AllowedValues:
      - S
      - N
      - B 
  SortKey:
    Description: This field is the secondary index of the table. (RANGE)
    Type: String
  SortKeyType:
    Description: Type of data that will be associated with the SortKey (S = String, N = Number)
    Type: String
    AllowedValues:
      - S
      - N
      - B 
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Tagging and billing
      Parameters:
      - Customer
      - CustomerProject
    - Label:
        default: Choose Branch and Environment
      Parameters:
      - Environment
      - BranchName
Resources:
  myDEVInventoryDB:
    Type: AWS::DynamoDB::Table
    Description: table of dynamodb              
    Properties:
      TableName: 
        !Join
        - ''
        - - !Ref ProjectName
          - !Ref Stage
          - !Ref Name          
      AttributeDefinitions:
        -
          AttributeName: !Ref PartitionKey
          AttributeType: !Ref PartitionKeyType
        -
          AttributeName: !Ref SortKey
          AttributeType: !Ref SortKeyType
        - 
          AttributeName: "description"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: !Ref PartitionKey
          KeyType: "HASH"
        -
          AttributeName: !Ref SortKey
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST       
      GlobalSecondaryIndexes: 
        - 
          IndexName: "Id_index"
          KeySchema: 
            - 
              AttributeName: !Ref PartitionKey
              KeyType: "HASH"
            - 
              AttributeName: "description"
              KeyType: "RANGE"
          Projection: 
            NonKeyAttributes: 
              - !Ref SortKey              
            ProjectionType: "INCLUDE"       
